cc_library(
  name = "strblob",
  srcs = [
    "str_blob.cc"
  ],
  deps = [
    "#gtest"
  ]
)

cc_test(
  name = "str_blob_test",
  srcs = [
    "str_blob_test.cc"
  ],
  deps = [
    ":strblob"
  ]
)
