cc_library(
  name = "text_query",
  srcs = [
    "text_query.cc",
    "text_query_impl.cc"
  ],
  deps = [
    ":string_util"
  ]
)

cc_library(
  name = "string_util",
  srcs = [
    "string_util.cc"
  ],
  deps = []
)

cc_test(
  name = "string_utl_test",
  srcs = [
    "string_util_test.cc"
  ],
  deps = [
    ":string_util"
  ]
)
